### PR TITLE
Update project to gradle structure

### PR DESCRIPTION
**Pull request by johncordeiro**
This PR converts the current project structure to gradle style, as requested on issue #9.

### CODE REVIEW

**Comment by ericnewcomer** [comment]
Hey @johncordeiro, nice to hear from you! At first blush it looks like this PR is including a lot of build files that shouldn't be in the repo. Maybe instead add them to the git ignore?

**Comment by johncordeiro** [comment]
Added on gitignore and applied on the project.

**Comment by nicpottier** [comment]
Sorry for the delay, finally had some time to look at this. Can we add one more thing before we launch, that is to add a sample Config.java so that it builds cleanly.. We can then maybe also add a .travis file to automate builds which would be a nice thing to have.

We'd like to invest a bit of time on the Android channel as well. Looking at our stats, seems we can move to our lowest Android version being 4.0.3 instead of supporting 2.3 which means we could move up to using Firebase messaging instead of GCM.

The other thing we'd like to do is make the changes necessary to deal with Doze on Android 5/6 so that the relayer works stays connected when there isn't any activity. But as a first step this move to Gradle seems great.

If you add in the Config.java we'll merge.

**Comment by johncordeiro** [comment]
@nicpottier default `Config.java` created!

**Pull request merged**
