### PR TITLE
Request for building apk for testing.

### PR DESCRIPTION
**Pull request by imwongela**
Hello Rapidpro team,

We have customized the android-channel app and we would like to build it. Unfortunately, we don't 
have the environment variables for the GCM(Google Cloud Messaging) to enable it to work properly. Please help us build and generate an apk for this or provide us with the GCM_API_KEY and GCM_APP_ID and any information that might be helpful.

Thanks,
Isaac

### CODE REVIEW

**Comment by mberg** [comment]
Please disregard this.  We need to make some modifications

**Comment by mberg** [comment]
The goal of this pull request is to allow adding custom URLs in the IP place.

Right now it appends automatically a port 8000 which makes pointing to another hosted instance of rapidpro impossible (unless you enable port 8000) and use the server's IP address.

We pushed up the wrong branch of code that does this so we are amending.

**Comment by norkans7** [comment]
You can use the IP address and include the port you want as 123.123.123.123:80 ; 
8000 is only considered if no port is given

**Comment by mberg** [comment]
Understood.

We are proposing adding the following

Changing IP to Server URL.  Here you can put in an IP address (with a port)
or a regular server URL if you want.

Making end users put in an IP address with ports is not very user friendly.
  I think we'd all prefer to be able to use the default rapidpro channel
app then having to publish customized versions.

Thanks,

Matt

**Comment by nicpottier** [comment]
So either way you are going to have to build your own app and ship it to the Play Store because of the GCM ids. These are specific to every install and private.

Happy to accept a PR to change the default not to append port 8000 on a custom server, but that isn't going to fix the GCM issue for you.

PS. Where are you hosting the ona instance and is your fork up to date, just curious as to any changes there.

**Comment by mberg** [comment]
Nic

We're hosting it here.  Mostly just to start testing it for now.

https://rapidpro.ona.io

It's up to date.  We got most of it working.  There are a few setup bugs
we're still hitting that we are trying to document and share back.

We also have an ansible playbook we'll share to the community once we get
this sorted.

Does the GCM ids apply to the server the app uses?  I don't understand how
this works well enough I guess.

Thanks,

Matt

**Comment by nicpottier** [comment]
Cool, looking forward to some PRs on those fixes for sure.

GCM is essentially Google's push messaging for Android handsets, it lets servers push a message to the handset:
   https://developers.google.com/cloud-messaging/

So ya, both your server and client have a shared GCM id (and associated App) that is used as the channel. The handset "registers" with that id on startup of the Android app using that id, then passes it to RapidPro when registering. RapidPro can then use that later to push a message to it, essentially notifying it to sync and get new messages from the server.

Those are specific to installs otherwise there's no way to know which app is requesting a sync.

**Comment by mberg** [comment]
Ah ok.

Maybe we should modify it then to allow us to plug in the GCM as a setting.

**Comment by nicpottier** [comment]
Sadly I don't think it is that easy, the GCM id is tied to the Android App and each App can only have one.

**Comment by mberg** [comment]
ah ok gotcha.  thanks for clarifying it.

Well let's start contributing to the core app and let people know they have
to deploy their own versions

**Comment by ericnewcomer** [comment]
Closing for inactivity

**Pull request closed without merging**
