### PR TITLE
Updates to use newer FCM

### PR DESCRIPTION
**Pull request by norkans7**

### CODE REVIEW

**Comment by nicpottier** [comment]
Ok cool, does this address any known problems? Doesn't it seem likely that this could actually introduce problems say on older devices? Just want to make sure we aren't making changes for the sake of making changes without identifying things as actually problematic.

**Comment by norkans7** [comment]
I think this fix the issue where the server will stop to be notified of the proper token when it is rotated
https://firebase.google.com/docs/reference/android/com/google/firebase/iid/FirebaseInstanceIdServic
I switched to use the described method to monitor the token 
https://firebase.google.com/docs/cloud-messaging/android/client

**Comment by nicpottier** [comment]
Ok, how have you tested this?

**Comment by norkans7** [comment]
Right, I see the case for token rotation will create a new channel instead.

**Comment by nicpottier** [comment]
Not sure I understand, tokens can certainly change FCM tokens (that happens in the sync) was just asking how this was tested.

**Comment by norkans7** [comment]
I think the only case the token can be changed is when the use clears the data and tried that and that requires a new registration. I do not have any other way to test that.
I am missing something?

**Comment by nicpottier** [comment]
Sorry, I wasn't asking about testing that particular case but rather the new library as a whole.

**Comment by norkans7** [comment]
I had sent a message from the server and used called manually https://github.com/nyaruka/rapidpro/blob/master/temba/channels/models.py#L1207 to see that the sync where actually happening correctly

**Comment by nicpottier** [comment]
Can you recreate this branch in that case?

**Pull request merged**
